// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env?.VITE_SUPABASE_URL || process.env?.VITE_SUPABASE_URL || "https://bspgctcbgjihpuosfxwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || process.env?.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcGdjdGNiZ2ppaHB1b3NmeHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM3MTc4OTksImV4cCI6MjA5OTI5Mzg5OX0.aguVd0-0QuEjp5lRv5t4MkP_c4QJqy9SKNgc8yYIc4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});