// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jswiztvbctkauqnvrvml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impzd2l6dHZiY3RrYXVxbnZydm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwODA4OTMsImV4cCI6MjA3OTY1Njg5M30.TYWUEz6mh6zSsuOiKljgw0ro9jBjp5Lv3b0ZILGFimc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});